engine:
    type: HighThroughputEngine
    worker_debug: False

    strategy:
        type: SimpleStrategy
        max_idletime: 30

    address:
        type: address_by_interface
        ifname: hsn0

    provider:
        type: SlurmProvider

        launcher:
            type: SimpleLauncher

        # Options prepended to the submit script. Set #SBATCH directives here:
        scheduler_options: "#SBATCH -q realtime -C cpu --licenses=scratch,cfs"

        # Job configuraton:
        account: m4386

        # Command to be run before starting a worker
        # e.g., "module load Anaconda; source activate parsl_env"
        worker_init: module load python/3.10; source /global/homes/c/chester/globus_flows/globus_compute_venv/bin/activate

        # increase the command timeouts
        cmd_timeout: 120

        # Scale between 0-5 blocks with 5 nodes per block
        nodes_per_block: 5
        init_blocks: 0
        min_blocks: 0
        max_blocks: 5

        # Hold blocks for 30 minutes
        walltime: 00:30:00