engine:
    type: HighThroughputEngine
    worker_debug: False
    max_workers_per_node: 256

    strategy:
        type: SimpleStrategy
        max_idletime: 30

    address:
        type: address_by_interface
        ifname: hsn0

    provider:
        type: SlurmProvider

        launcher:
            type: SimpleLauncher

        # Options prepended to the submit script. Set #SBATCH directives here:
        scheduler_options: "#SBATCH -q realtime -C cpu --licenses=scratch,cfs -n 1 -c 1"

        # Job configuraton:
        account: m4386

        # Command to be run before starting a worker
        # e.g., "module load Anaconda; source activate parsl_env"
        worker_init: module load python/3.10; source /global/homes/c/chester/globus_flows/globus_compute_venv/bin/activate

        # Increase the command timeouts
        cmd_timeout: 120

        # Define provisioned resources:
        nodes_per_block: 1
        init_blocks: 0
        min_blocks: 0
        max_blocks: 5

        # Hold blocks for 1.5 hrs for conversion
        walltime: 01:30:00